env:
  - CXX=g++-4.8

language: node_js
node_js:
  - "4"
  - "5"
  - "6"
  - "7"
script:
  - npm run lint:test
cache:
  yarn: true
  directories:
    - node_modules

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
